# Generated by Django 5.0.4 on 2024-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_tagpost'),
        ('women', '0007_alter_women_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='cats.tagpost'),
        ),
    ]
