# Generated by Django 5.0.4 on 2024-05-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_tagpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
