# Generated by Django 5.0.4 on 2024-05-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
